### ISSUE TITLE
Vue index has static references to localhost:8998

### ISSUE THREAD

**Issue by aarontp** [crhuber/golinks#5]
If golinks is served on a different host from the client the XHR calls to the `/api/v1/links` endpoint fail because they are going to localhost:8998 (even if the port is set to something else) and so new golinks cannot be saved.  It appears this is due to the index page having several static references to localhost:8998, for example: https://github.com/crhuber/golinks/blob/0fc7b8c3a40d9a1dce775f560c673410b3f12249/pkg/server/static/index.html#L166

Changing all these references in index.html to match the installation seems to work.   Maybe this could be parameterized in another command line or ENV parameter.

**Comment by crhuber** [comment]
fixed in 0.0.9 https://github.com/crhuber/golinks/releases/tag/0.0.9

**Comment by aarontp** [comment]
Awesome, thanks for the fast fix!
