### ISSUE TITLE
Destinations without HTTP prefix are interpreted as keywords

### ISSUE THREAD

**Issue by vterron** [crhuber/golinks#7]
Destinations without an `http://` prefix don't seem to work properly. Take, for example:

![2023-11-03-212002_1169x455_scrot](https://github.com/crhuber/golinks/assets/1575425/a78a8e91-5ae4-41de-9c8f-98c336cbbc2d)

Typing `http://go:8998/google` in the browser takes me to:

![2023-11-03-212026_1182x480_scrot](https://github.com/crhuber/golinks/assets/1575425/8213aea7-831b-4442-b43f-16f8c3265b34)

From the logs:

```
{"level":"info","msg":"127.0.0.1:56036 GET /google","time":"2023-11-03T21:25:40+01:00"}
{"level":"info","msg":"127.0.0.1:56036 GET /google.com","time":"2023-11-03T21:25:40+01:00"}

2023/11/03 21:25:40 /home/vterron/code/golinks/pkg/controllers/keyword.go:26 record not found
[78.770ms] [rows:0] SELECT * FROM `links` WHERE keyword = "google.com" ORDER BY `links`.`id` LIMIT 1
{"level":"info","msg":"keyword not found  in exact match. trying wildcard","time":"2023-11-03T21:25:40+01:00"}

2023/11/03 21:25:40 /home/vterron/code/golinks/pkg/controllers/keyword.go:31 record not found
[0.122ms] [rows:0] SELECT * FROM `links` WHERE keyword = "google.com/{*}" ORDER BY `links`.`id` LIMIT 1
{"level":"info","msg":"127.0.0.1:56036 GET /?q=google.com","time":"2023-11-03T21:25:40+01:00"}
{"level":"info","msg":"127.0.0.1:56036 GET /api/v1/links","time":"2023-11-03T21:25:40+01:00"}
```
It seems that the **destination is being interpreted as a keyword**.

Typing `http://go:8998/bing` in the browser, on the other hand, forwards to `bing.com` as expected.

Is this intentional? I can try to submit a fix if you confirm this is indeed a bug.

**Comment by crhuber** [comment]
@vterron its definitely not intentional. 
Ideally It should have url validation before saving to prevent links without http or https. I believe I had this at one point but dropped it because it was too strict and was causing some urls to fail. 
I'll have a second look and try to fix this

**Comment by crhuber** [comment]
fixed in latest release https://github.com/crhuber/golinks/releases/tag/0.0.11

**Comment by vterron** [comment]
I can confirm the fix works. Thanks!

**Comment by vterron** [comment]
Not so fast — just noticed that the validator is rejecting _all_ URLs, e.g:

![2023-11-09-232638_701x456_scrot](https://github.com/crhuber/golinks/assets/1575425/a7ccc153-46ba-4551-9814-9483bc6d778c)

The problem is in the `if` statement [here](https://github.com/crhuber/golinks/blob/639546f6424d1d37a7dc67b0e4dfef171f82729a/pkg/models/link.go#L36): we need `not(x or y)`, but have:

```
if !(strings.HasPrefix(s, "http:")) || !(strings.HasPrefix(s, "https:")) {
    return errors.New("requires scheme http or https")
}
```

**Comment by vterron** [comment]
Sent a fix in https://github.com/crhuber/golinks/pull/9.

**Comment by crhuber** [comment]
ooops good catch
